import html
from pathlib import Path
from db import init_db,load_daily,load_predictions,load_scored
OUT=Path(__file__).parent/"site"/"index.html"
def main():
    init_db();d=load_daily();p=load_predictions();s=load_scored();latest=p.base_date.max() if not p.empty else "-";rows=p[p.base_date==latest] if not p.empty else p;ens=rows[rows.agent=="ENSEMBLE"];prob=float(ens.prob_up.iloc[0]) if not ens.empty else None
    table="".join(f"<tr><td>{html.escape(str(r.agent))}</td><td>{r.prob_up:.1%}</td><td>{html.escape(str(r.reason))}</td></tr>" for _,r in rows.iterrows());stats="".join(f"<tr><td>{html.escape(str(a))}</td><td>{len(g)}</td><td>{g.correct.mean():.1%}</td><td>{g.brier.mean():.4f}</td></tr>" for a,g in s.groupby("agent")) if not s.empty else ""
    price=f"{d.close.iloc[-1]:,.2f}" if not d.empty else "-";probtext=f"{prob:.1%}" if prob is not None else "-";direction="偏多" if prob and prob>.5 else "偏空" if prob is not None else "-"
    OUT.write_text("""<!doctype html><html lang='zh-CN'><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>上证指数多智能体看板</title><style>body{font-family:system-ui;max-width:1100px;margin:40px auto;padding:0 18px;background:#f7f7f8}.card{background:white;border:1px solid #ddd;border-radius:14px;padding:20px;margin:14px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.big{font-size:34px;font-weight:700}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #eee;text-align:left}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style><body><h1>上证指数多智能体预测</h1><p>自动生成于 GitHub Actions；仅供研究，不构成投资建议。</p><div class='grid'><div class='card'>最新收盘<div class='big'>"""+price+"""</div></div><div class='card'>预测基准日<div class='big'>"""+latest+"""</div></div><div class='card'>下一交易日上涨概率<div class='big'>"""+probtext+" """+direction+"</div></div></div><div class='card'><h2>最新各 Agent</h2><table><tr><th>Agent</th><th>上涨概率</th><th>理由</th></tr>"""+table+"""</table></div><div class='card'><h2>历史战绩</h2><table><tr><th>Agent</th><th>样本</th><th>方向准确率</th><th>Brier</th></tr>"""+stats+"""</table></div></body></html>""",encoding="utf-8")
if __name__=="__main__":main()
